version: 1
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
faucet:
  name: bob
  coins:
  - 5token
  - 100000stake
client:
  typescript:
    path: ../test-frontend/ts-client
  hooks:
    path: ../test-frontend/react/src/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
