// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: blockchain/identity/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRegisterParticipant struct {
	Creator  string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (m *MsgRegisterParticipant) Reset()         { *m = MsgRegisterParticipant{} }
func (m *MsgRegisterParticipant) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterParticipant) ProtoMessage()    {}
func (*MsgRegisterParticipant) Descriptor() ([]byte, []int) {
	return fileDescriptor_13deadb02d6524bf, []int{0}
}
func (m *MsgRegisterParticipant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterParticipant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterParticipant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterParticipant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterParticipant.Merge(m, src)
}
func (m *MsgRegisterParticipant) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterParticipant) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterParticipant.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterParticipant proto.InternalMessageInfo

func (m *MsgRegisterParticipant) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRegisterParticipant) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type MsgRegisterParticipantResponse struct {
}

func (m *MsgRegisterParticipantResponse) Reset()         { *m = MsgRegisterParticipantResponse{} }
func (m *MsgRegisterParticipantResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterParticipantResponse) ProtoMessage()    {}
func (*MsgRegisterParticipantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13deadb02d6524bf, []int{1}
}
func (m *MsgRegisterParticipantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterParticipantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterParticipantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterParticipantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterParticipantResponse.Merge(m, src)
}
func (m *MsgRegisterParticipantResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterParticipantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterParticipantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterParticipantResponse proto.InternalMessageInfo

type MsgCreateTeam struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *MsgCreateTeam) Reset()         { *m = MsgCreateTeam{} }
func (m *MsgCreateTeam) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTeam) ProtoMessage()    {}
func (*MsgCreateTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_13deadb02d6524bf, []int{2}
}
func (m *MsgCreateTeam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateTeam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTeam.Merge(m, src)
}
func (m *MsgCreateTeam) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTeam.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTeam proto.InternalMessageInfo

func (m *MsgCreateTeam) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateTeam) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MsgCreateTeamResponse struct {
}

func (m *MsgCreateTeamResponse) Reset()         { *m = MsgCreateTeamResponse{} }
func (m *MsgCreateTeamResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateTeamResponse) ProtoMessage()    {}
func (*MsgCreateTeamResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13deadb02d6524bf, []int{3}
}
func (m *MsgCreateTeamResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateTeamResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateTeamResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateTeamResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateTeamResponse.Merge(m, src)
}
func (m *MsgCreateTeamResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateTeamResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateTeamResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateTeamResponse proto.InternalMessageInfo

type MsgSetTeamManager struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Team    string `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Manager string `protobuf:"bytes,3,opt,name=manager,proto3" json:"manager,omitempty"`
}

func (m *MsgSetTeamManager) Reset()         { *m = MsgSetTeamManager{} }
func (m *MsgSetTeamManager) String() string { return proto.CompactTextString(m) }
func (*MsgSetTeamManager) ProtoMessage()    {}
func (*MsgSetTeamManager) Descriptor() ([]byte, []int) {
	return fileDescriptor_13deadb02d6524bf, []int{4}
}
func (m *MsgSetTeamManager) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetTeamManager) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetTeamManager.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetTeamManager) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetTeamManager.Merge(m, src)
}
func (m *MsgSetTeamManager) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetTeamManager) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetTeamManager.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetTeamManager proto.InternalMessageInfo

func (m *MsgSetTeamManager) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetTeamManager) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *MsgSetTeamManager) GetManager() string {
	if m != nil {
		return m.Manager
	}
	return ""
}

type MsgSetTeamManagerResponse struct {
}

func (m *MsgSetTeamManagerResponse) Reset()         { *m = MsgSetTeamManagerResponse{} }
func (m *MsgSetTeamManagerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetTeamManagerResponse) ProtoMessage()    {}
func (*MsgSetTeamManagerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13deadb02d6524bf, []int{5}
}
func (m *MsgSetTeamManagerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetTeamManagerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetTeamManagerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetTeamManagerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetTeamManagerResponse.Merge(m, src)
}
func (m *MsgSetTeamManagerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetTeamManagerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetTeamManagerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetTeamManagerResponse proto.InternalMessageInfo

type MsgSetTeamTrainer struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Team    string `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	Trainer string `protobuf:"bytes,3,opt,name=trainer,proto3" json:"trainer,omitempty"`
}

func (m *MsgSetTeamTrainer) Reset()         { *m = MsgSetTeamTrainer{} }
func (m *MsgSetTeamTrainer) String() string { return proto.CompactTextString(m) }
func (*MsgSetTeamTrainer) ProtoMessage()    {}
func (*MsgSetTeamTrainer) Descriptor() ([]byte, []int) {
	return fileDescriptor_13deadb02d6524bf, []int{6}
}
func (m *MsgSetTeamTrainer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetTeamTrainer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetTeamTrainer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetTeamTrainer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetTeamTrainer.Merge(m, src)
}
func (m *MsgSetTeamTrainer) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetTeamTrainer) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetTeamTrainer.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetTeamTrainer proto.InternalMessageInfo

func (m *MsgSetTeamTrainer) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSetTeamTrainer) GetTeam() string {
	if m != nil {
		return m.Team
	}
	return ""
}

func (m *MsgSetTeamTrainer) GetTrainer() string {
	if m != nil {
		return m.Trainer
	}
	return ""
}

type MsgSetTeamTrainerResponse struct {
}

func (m *MsgSetTeamTrainerResponse) Reset()         { *m = MsgSetTeamTrainerResponse{} }
func (m *MsgSetTeamTrainerResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetTeamTrainerResponse) ProtoMessage()    {}
func (*MsgSetTeamTrainerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13deadb02d6524bf, []int{7}
}
func (m *MsgSetTeamTrainerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetTeamTrainerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetTeamTrainerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetTeamTrainerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetTeamTrainerResponse.Merge(m, src)
}
func (m *MsgSetTeamTrainerResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetTeamTrainerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetTeamTrainerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetTeamTrainerResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgRegisterParticipant)(nil), "internetofsports.blockchain.identity.MsgRegisterParticipant")
	proto.RegisterType((*MsgRegisterParticipantResponse)(nil), "internetofsports.blockchain.identity.MsgRegisterParticipantResponse")
	proto.RegisterType((*MsgCreateTeam)(nil), "internetofsports.blockchain.identity.MsgCreateTeam")
	proto.RegisterType((*MsgCreateTeamResponse)(nil), "internetofsports.blockchain.identity.MsgCreateTeamResponse")
	proto.RegisterType((*MsgSetTeamManager)(nil), "internetofsports.blockchain.identity.MsgSetTeamManager")
	proto.RegisterType((*MsgSetTeamManagerResponse)(nil), "internetofsports.blockchain.identity.MsgSetTeamManagerResponse")
	proto.RegisterType((*MsgSetTeamTrainer)(nil), "internetofsports.blockchain.identity.MsgSetTeamTrainer")
	proto.RegisterType((*MsgSetTeamTrainerResponse)(nil), "internetofsports.blockchain.identity.MsgSetTeamTrainerResponse")
}

func init() { proto.RegisterFile("blockchain/identity/tx.proto", fileDescriptor_13deadb02d6524bf) }

var fileDescriptor_13deadb02d6524bf = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xbf, 0x4e, 0xe3, 0x40,
	0x10, 0xc6, 0xe3, 0x4b, 0x74, 0x7f, 0x56, 0xba, 0x93, 0xce, 0xa7, 0xbb, 0x33, 0x06, 0x59, 0x91,
	0x45, 0x41, 0x65, 0x4b, 0xa4, 0x48, 0x01, 0x08, 0x09, 0x68, 0x28, 0xcc, 0x9f, 0x24, 0x15, 0x54,
	0x1b, 0x33, 0x71, 0x56, 0xc1, 0xbb, 0xd6, 0xee, 0x20, 0x25, 0x0d, 0x0f, 0x40, 0x45, 0xcb, 0xb3,
	0xf0, 0x02, 0x94, 0x29, 0x29, 0x51, 0xf2, 0x22, 0x28, 0x8e, 0x9d, 0x38, 0xc1, 0x8a, 0x92, 0xd0,
	0x79, 0xbc, 0xf3, 0x7d, 0xbf, 0x4f, 0x9a, 0xd1, 0x90, 0xad, 0xe6, 0xad, 0xf0, 0x3b, 0x7e, 0x9b,
	0x32, 0xee, 0xb2, 0x1b, 0xe0, 0xc8, 0xb0, 0xe7, 0x62, 0xd7, 0x89, 0xa4, 0x40, 0xa1, 0x6f, 0x33,
	0x8e, 0x20, 0x39, 0xa0, 0x68, 0xa9, 0x48, 0x48, 0x54, 0xce, 0xb4, 0xdd, 0x49, 0xdb, 0xed, 0x33,
	0xf2, 0xcf, 0x53, 0x41, 0x0d, 0x02, 0xa6, 0x10, 0xe4, 0x05, 0x95, 0xc8, 0x7c, 0x16, 0x51, 0x8e,
	0xba, 0x41, 0xbe, 0xf9, 0x12, 0x28, 0x0a, 0x69, 0x68, 0x65, 0x6d, 0xe7, 0x47, 0x2d, 0x2d, 0x75,
	0x93, 0x7c, 0xe7, 0xcc, 0xef, 0x70, 0x1a, 0x82, 0xf1, 0x25, 0x7e, 0x9a, 0xd4, 0x76, 0x99, 0x58,
	0xf9, 0x7e, 0x35, 0x50, 0x91, 0xe0, 0x0a, 0xec, 0x03, 0xf2, 0xd3, 0x53, 0xc1, 0xf1, 0xc8, 0x0b,
	0x1a, 0x40, 0xc3, 0x05, 0x20, 0x9d, 0x94, 0x32, 0x90, 0xf8, 0xdb, 0xfe, 0x4f, 0xfe, 0xce, 0xc8,
	0x27, 0xbe, 0xd7, 0xe4, 0xb7, 0xa7, 0x82, 0x3a, 0xe0, 0xe8, 0xaf, 0x47, 0x39, 0x0d, 0x40, 0x2e,
	0xf6, 0x46, 0xa0, 0x61, 0xea, 0x8d, 0x49, 0x92, 0x70, 0x2c, 0x34, 0x8a, 0xe3, 0xee, 0xa4, 0xb4,
	0x37, 0xc9, 0xc6, 0x07, 0xf3, 0x7c, 0x72, 0x43, 0x52, 0xc6, 0xd7, 0x21, 0xe3, 0x58, 0x98, 0x92,
	0x93, 0x72, 0x96, 0x9c, 0x98, 0xa7, 0xe4, 0xdd, 0xe7, 0x12, 0x29, 0x7a, 0x2a, 0xd0, 0x9f, 0x34,
	0xf2, 0x27, 0x6f, 0x86, 0xfb, 0xce, 0x32, 0x4b, 0xe0, 0xe4, 0x4f, 0xcc, 0x3c, 0xf9, 0x8c, 0x3a,
	0xcd, 0xa8, 0xdf, 0x13, 0x92, 0x19, 0x76, 0x65, 0x69, 0xcf, 0xa9, 0xc8, 0xdc, 0x5b, 0x43, 0x34,
	0xe1, 0x3f, 0x68, 0xe4, 0xd7, 0xdc, 0x56, 0x54, 0x97, 0xf6, 0x9b, 0x15, 0x9a, 0x87, 0x6b, 0x0a,
	0xf3, 0xc2, 0xa4, 0x8b, 0xb2, 0x72, 0x98, 0x44, 0xb8, 0x7a, 0x98, 0xb9, 0xed, 0x39, 0xba, 0x7c,
	0x19, 0x58, 0x5a, 0x7f, 0x60, 0x69, 0x6f, 0x03, 0x4b, 0x7b, 0x1c, 0x5a, 0x85, 0xfe, 0xd0, 0x2a,
	0xbc, 0x0e, 0xad, 0xc2, 0x55, 0x35, 0x60, 0xd8, 0xbe, 0x6b, 0x3a, 0xbe, 0x08, 0xdd, 0xd3, 0x04,
	0x72, 0xde, 0xaa, 0xc7, 0x10, 0x37, 0x73, 0x75, 0xba, 0x99, 0xbb, 0xd3, 0x8b, 0x40, 0x35, 0xbf,
	0xc6, 0xb7, 0xa7, 0xf2, 0x1e, 0x00, 0x00, 0xff, 0xff, 0x71, 0x32, 0x4c, 0xcb, 0x9b, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RegisterParticipant(ctx context.Context, in *MsgRegisterParticipant, opts ...grpc.CallOption) (*MsgRegisterParticipantResponse, error)
	CreateTeam(ctx context.Context, in *MsgCreateTeam, opts ...grpc.CallOption) (*MsgCreateTeamResponse, error)
	SetTeamManager(ctx context.Context, in *MsgSetTeamManager, opts ...grpc.CallOption) (*MsgSetTeamManagerResponse, error)
	SetTeamTrainer(ctx context.Context, in *MsgSetTeamTrainer, opts ...grpc.CallOption) (*MsgSetTeamTrainerResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RegisterParticipant(ctx context.Context, in *MsgRegisterParticipant, opts ...grpc.CallOption) (*MsgRegisterParticipantResponse, error) {
	out := new(MsgRegisterParticipantResponse)
	err := c.cc.Invoke(ctx, "/internetofsports.blockchain.identity.Msg/RegisterParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateTeam(ctx context.Context, in *MsgCreateTeam, opts ...grpc.CallOption) (*MsgCreateTeamResponse, error) {
	out := new(MsgCreateTeamResponse)
	err := c.cc.Invoke(ctx, "/internetofsports.blockchain.identity.Msg/CreateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetTeamManager(ctx context.Context, in *MsgSetTeamManager, opts ...grpc.CallOption) (*MsgSetTeamManagerResponse, error) {
	out := new(MsgSetTeamManagerResponse)
	err := c.cc.Invoke(ctx, "/internetofsports.blockchain.identity.Msg/SetTeamManager", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetTeamTrainer(ctx context.Context, in *MsgSetTeamTrainer, opts ...grpc.CallOption) (*MsgSetTeamTrainerResponse, error) {
	out := new(MsgSetTeamTrainerResponse)
	err := c.cc.Invoke(ctx, "/internetofsports.blockchain.identity.Msg/SetTeamTrainer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RegisterParticipant(context.Context, *MsgRegisterParticipant) (*MsgRegisterParticipantResponse, error)
	CreateTeam(context.Context, *MsgCreateTeam) (*MsgCreateTeamResponse, error)
	SetTeamManager(context.Context, *MsgSetTeamManager) (*MsgSetTeamManagerResponse, error)
	SetTeamTrainer(context.Context, *MsgSetTeamTrainer) (*MsgSetTeamTrainerResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RegisterParticipant(ctx context.Context, req *MsgRegisterParticipant) (*MsgRegisterParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterParticipant not implemented")
}
func (*UnimplementedMsgServer) CreateTeam(ctx context.Context, req *MsgCreateTeam) (*MsgCreateTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (*UnimplementedMsgServer) SetTeamManager(ctx context.Context, req *MsgSetTeamManager) (*MsgSetTeamManagerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTeamManager not implemented")
}
func (*UnimplementedMsgServer) SetTeamTrainer(ctx context.Context, req *MsgSetTeamTrainer) (*MsgSetTeamTrainerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTeamTrainer not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RegisterParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterParticipant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internetofsports.blockchain.identity.Msg/RegisterParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterParticipant(ctx, req.(*MsgRegisterParticipant))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateTeam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internetofsports.blockchain.identity.Msg/CreateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateTeam(ctx, req.(*MsgCreateTeam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetTeamManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetTeamManager)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetTeamManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internetofsports.blockchain.identity.Msg/SetTeamManager",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetTeamManager(ctx, req.(*MsgSetTeamManager))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetTeamTrainer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetTeamTrainer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetTeamTrainer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internetofsports.blockchain.identity.Msg/SetTeamTrainer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetTeamTrainer(ctx, req.(*MsgSetTeamTrainer))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internetofsports.blockchain.identity.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterParticipant",
			Handler:    _Msg_RegisterParticipant_Handler,
		},
		{
			MethodName: "CreateTeam",
			Handler:    _Msg_CreateTeam_Handler,
		},
		{
			MethodName: "SetTeamManager",
			Handler:    _Msg_SetTeamManager_Handler,
		},
		{
			MethodName: "SetTeamTrainer",
			Handler:    _Msg_SetTeamTrainer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blockchain/identity/tx.proto",
}

func (m *MsgRegisterParticipant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterParticipant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterParticipant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nickname) > 0 {
		i -= len(m.Nickname)
		copy(dAtA[i:], m.Nickname)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Nickname)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterParticipantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterParticipantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterParticipantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateTeam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateTeam) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateTeam) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateTeamResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateTeamResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateTeamResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetTeamManager) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetTeamManager) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetTeamManager) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Manager) > 0 {
		i -= len(m.Manager)
		copy(dAtA[i:], m.Manager)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Manager)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Team) > 0 {
		i -= len(m.Team)
		copy(dAtA[i:], m.Team)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Team)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetTeamManagerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetTeamManagerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetTeamManagerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetTeamTrainer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetTeamTrainer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetTeamTrainer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Trainer) > 0 {
		i -= len(m.Trainer)
		copy(dAtA[i:], m.Trainer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Trainer)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Team) > 0 {
		i -= len(m.Team)
		copy(dAtA[i:], m.Team)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Team)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetTeamTrainerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetTeamTrainerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetTeamTrainerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRegisterParticipant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Nickname)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRegisterParticipantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateTeam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateTeamResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetTeamManager) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Team)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Manager)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetTeamManagerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetTeamTrainer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Team)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Trainer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetTeamTrainerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRegisterParticipant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterParticipant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterParticipant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nickname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nickname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterParticipantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterParticipantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterParticipantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateTeam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateTeam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateTeam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateTeamResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateTeamResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateTeamResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetTeamManager) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetTeamManager: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetTeamManager: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Team = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Manager", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Manager = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetTeamManagerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetTeamManagerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetTeamManagerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetTeamTrainer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetTeamTrainer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetTeamTrainer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Team", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Team = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Trainer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Trainer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetTeamTrainerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetTeamTrainerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetTeamTrainerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
